#!/usr/bin/env bash

# Copyright (c) 2023 Nick Piaddo
# SPDX-License-Identifier: Apache-2.0 OR MIT

################################################################################
# Description
#
# ssh-test-vm:
#   SCP wrapper to copy files from/to a virtual machine to test the
#  `nixos-fde-config` script.
#   QEMU monitor port: telnet 45454
#   SSH port: 2222
#
################################################################################

# Coding convention
#
# CAPITAL_SNAKE_CASE: global variable
# snake_case: local variable
# camelCase: function

# Script template inspired by
# https://sharats.me/posts/shell-script-best-practices/
set -o errexit
set -o nounset
set -o pipefail
shopt -s globstar
shopt -s nullglob

# Run script `TRACE=1 ./scp-test-vm' to enable debug mode
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

passh -p '' scp -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no \
  -oPasswordAuthentication=yes -P 2222 -- "$@"
