#!/usr/bin/env bash

# Copyright (c) 2023 Nick Piaddo
# SPDX-License-Identifier: Apache-2.0 OR MIT

################################################################################
# Description
#
# start-test-vm:
#   starts a virtual machine to test the `nixos-fde-config` script.
#   QEMU monitor port: telnet 45454
#   SSH port: 2222
#
################################################################################

# Coding convention
#
# CAPITAL_SNAKE_CASE: global variable
# snake_case: local variable
# camelCase: function

# Script template inspired by
# https://sharats.me/posts/shell-script-best-practices/
set -o errexit
set -o nounset
set -o pipefail
shopt -s globstar
shopt -s nullglob

# Run script `TRACE=1 ./start-test-vm' to enable debug mode
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
BASE_DIR="$(realpath "${DIR}/../")"
CONF_DIR="${BASE_DIR}/config"
SCRIPTS_DIR="${BASE_DIR}/scripts"
VM_DIR="${BASE_DIR}/area51/test-vm"

# VM SSH port redirection
VM_SSH_PORT=2222
# VM monitor listening port
VM_MONITOR_PORT=45454
VM_SNAPSHOT="basevm"

if [[ ! -d "${VM_DIR}" ]]; then
  "${SCRIPTS_DIR}"/build-vm \
    "${CONF_DIR}"/no-root-password-install-iso.nix \
    --output "${VM_DIR}" \
    --monitor-port ${VM_MONITOR_PORT} \
    --ssh-port ${VM_SSH_PORT} \
    --save-snapshot ${VM_SNAPSHOT}
fi

"${SCRIPTS_DIR}"/start-vm "${VM_DIR}" "${VM_MONITOR_PORT}" "${VM_SSH_PORT}" -l "${VM_SNAPSHOT}"
