#!/usr/bin/env bash

# Copyright (c) 2023 Nick Piaddo
# SPDX-License-Identifier: Apache-2.0 OR MIT

################################################################################
# Description
#
# init-repo-submodules:
#   Initialize repository submodules.
#
################################################################################

# Coding convention
#
# CAPITAL_SNAKE_CASE: global variable
# snake_case: local variable
# camelCase: function

# Script template inspired by
# https://sharats.me/posts/shell-script-best-practices/
set -o errexit
set -o nounset
set -o pipefail
shopt -s globstar
shopt -s nullglob

# Run script `TRACE=1 ./build-test-harness [options]' to enable tracing
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

################################################################################
#                        GLOBAL VARIABLES
################################################################################
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
TEST_HELPERS="${DIR}/../tests/test_helper"

######################################################################
# Test if a path leads to an empty directory.
# Arguments:
#   Path
# Returns:
#   True if Path is an empty directory
#   False otherwise
######################################################################
function isEmptyDir { [[ -d "$1" && -z "$(ls -A "$1")" ]]; }

if isEmptyDir "${TEST_HELPERS}/bats-support" \
  || isEmptyDir "${TEST_HELPERS}/bats-assert" \
  || isEmptyDir "${TEST_HELPERS}/bats-file" \
  ; then
  git submodule update --init --recursive
fi
